# Numpy
* NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.
* Travis Oliphant created NumPy package in 2005 by injecting the features of the ancestor module Numeric into another module Numarray.
* It is an extension module of Python which is mostly written in C

In [ ]:
import numpy as np
# creating 1d array
print('creating 1d array')
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('-------------------------------------')

# creating 2d array
print('creating 2d array')
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print('-------------------------------------')

# creating 3d array
print('creating 3d array')
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)
print('-------------------------------------')

creating 1d array
[1 2 3 4 5]
-------------------------------------
creating 2d array
[[1 2 3]
 [4 5 6]]
-------------------------------------
creating 3d array
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
-------------------------------------


* numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
  * dtype -->	We can change the data type of the array elements by changing this option to the specified type. The default is none.
  * order -->	There can be 3 possible values assigned to this option. It can be C (column order), R (row order), or A (any)
  * ndmin -->	It represents the minimum dimensions of the resultant array.

In [ ]:
a = np.array([[1, 3, 5, 7], [4, 5, 6,3]] ,dtype=complex,ndmin=4)
print(a)

[[[[1.+0.j 3.+0.j 5.+0.j 7.+0.j]
   [4.+0.j 5.+0.j 6.+0.j 3.+0.j]]]]


### some attributes
* ndarray.ndim ---> for check the dimension of array
  * note --> ndim is not a function
* ndarray.shape --> give size based on row or column
* ndarray.size ---> how many elements in array
* ndarray.dtype --> datatype of each element

In [ ]:
print(arr2.ndim)
# print(arr2.ndim)
# print(arr3.ndim)


print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(2, 3)
6
int64


### max(), min(), and sum() functions


In [ ]:
print('min() function ',arr2.min())
print('max() function ',arr2.max())
print('sum() function ',arr2.sum())

min() function  1
max() function  6
sum() function  21


### Array Indexing or accessing

In [ ]:
print('accessing element in 1d array')
print(arr[2])
print('------------------------------')

print('accessing element in 2d array')
print(arr2[1,2])
print('------------------------------')

print('accessing element in 3d array')
print(arr3[1,1,0])
print('------------------------------')

accessing element in 1d array
3
------------------------------
accessing element in 2d array
6
------------------------------
accessing element in 3d array
4
------------------------------


### Slicing in array
* [ start : end : step ]

In [ ]:
# Slicing in 1d array
print('Slicing in 1d array')
array = np.array([1, 2, 3, 4, 5, 6, 7])

print(array[1:3])
print(array[1:])
print(array[:3])

# step slicing in 1d array
print('step slicing in 1d array')
print(array[0:5:2])

Slicing in 1d array
[2 3]
[2 3 4 5 6 7]
[1 2 3]
step slicing in 1d array
[1 3 5]


In [ ]:
# Slicing in 2d array
print('Slicing in 2d array')
array2 = np.array([[1, 2, 3, 4, 5, 6, 7],[9,8,7,6,5,4,3]])

print(array2[1,1:3])
print(array2[0,1:])
print(array2[1,:3])

# step slicing in 2d array
print('step slicing in 2d array')
print(array2[1,0:5:2])

Slicing in 2d array
[8 7]
[2 3 4 5 6 7]
[9 8 7]
step slicing in 2d array
[9 7 5]


## Data Types in NumPy
* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [ ]:
# convert array datatype while creating array
print('convert array datatype while creating array')
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

convert array datatype while creating array
[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# convert array datatype after creating array
# use of astype()
print('convert array datatype after creating array')
print('use of astype()')
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

convert array datatype after creating array
use of astype()
[1 2 3]
int32


### copy() or view()
* agar tum copied array mein kuch change kroge to wo original array mein reflect nhi hoga
* agar tum viewed array mein changement kroge to original array mein reflect hoga

-----------------------------------------------------------
* agar arr.base() == none aaye to array copied hai
* agar arr.base() == kuch or aaye to smjho ki array viewed hai kisi ka

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
y=arr.copy()
x = arr.view()
y[1]=55
x[0] = 31

print('original array ' ,arr)
print('copied array ' ,y)
print('viewed array ' ,x)

original array  [31  2  3  4  5]
copied array  [ 1 55  3  4  5]
viewed array  [31  2  3  4  5]


### np.sort(arr)

In [ ]:
# Sort a boolean array:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
# sorting in 1d array
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
# sorting in 2d array
print('sorting in 2d array')
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Reshape

In [ ]:
# Reshape in 1d to 2d array
print('Reshape in 1d to 2d array')
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

print('--------------------------------------------')
print('check new array is copied or view')
print(newarr.base)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------------------------------
check new array is copied or view
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Reshape in 1d to 3d array
print('Reshape in 1d to 3d array')
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

Reshape in 1d to 3d array
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Iteration

In [ ]:
# Iteration in 1d array
print('Iteration in 1d array')
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
# Iteration in 2d array
print('Iteration in 2d array')
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

print('-----------------------------------------')
for x in arr:
  for y in x:
    print(y)

Iteration in 2d array
[1 2 3]
[4 5 6]
-----------------------------------------
1
2
3
4
5
6


### Iterating Arrays Using nditer()

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Enumerated Iteration Using ndenumerate()

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


where() it gives all indexes

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

y = np.where(arr%2 == 1)

print(y)

(array([3, 5, 6]),)
