In [1]:
from sklearn.datasets import load_digits
import numpy as np
dic=load_digits()
print(dic.keys())




dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])


In [2]:
dic['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [3]:
dic['data'].shape

(1797, 64)

In [4]:
arr=dic['data'][2]
print(arr)

[ 0.  0.  0.  4. 15. 12.  0.  0.  0.  0.  3. 16. 15. 14.  0.  0.  0.  0.
  8. 13.  8. 16.  0.  0.  0.  0.  1.  6. 15. 11.  0.  0.  0.  1.  8. 13.
 15.  1.  0.  0.  0.  9. 16. 16.  5.  0.  0.  0.  0.  3. 13. 16. 16. 11.
  5.  0.  0.  0.  0.  3. 11. 16.  9.  0.]


In [5]:
import pandas as pd
df=pd.DataFrame(dic['data'],columns=dic['feature_names'])

In [6]:
X=df
y=dic['target']

In [7]:
# step 1 ==> Standardization
from sklearn.preprocessing import StandardScaler
model1=StandardScaler()
X_scaled=model1.fit_transform(X)
print(X_scaled)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


In [8]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov(df)
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[27.29265873  6.79613095 10.8531746  ... 17.3640873  22.63095238
  17.41666667]
 [ 6.79613095 42.51165675 27.7718254  ... 32.96676587 22.23214286
  22.06150794]
 [10.8531746  27.7718254  40.3015873  ... 31.66269841 19.26984127
  25.23809524]
 ...
 [17.3640873  32.96676587 31.66269841 ... 46.13392857 27.28174603
  36.62301587]
 [22.63095238 22.23214286 19.26984127 ... 27.28174603 39.15873016
  27.66666667]
 [17.41666667 22.06150794 25.23809524 ... 36.62301587 27.66666667
  40.26984127]]


In [9]:


# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)
print(eigen_values , eigen_vectors)

#)

[ 3.24977883e+04+0.00000000e+00j  5.10266928e+03+0.00000000e+00j
  4.63827452e+03+0.00000000e+00j ...  4.31984208e-15-4.49034287e-15j
 -6.24942175e-15+0.00000000e+00j -7.11678699e-15+0.00000000e+00j] [[ 0.0191148 +0.00000000e+00j  0.00232528+0.00000000e+00j
  -0.03867784+0.00000000e+00j ...  0.00024649+2.92608400e-04j
   0.0055724 +0.00000000e+00j  0.00597612+0.00000000e+00j]
 [ 0.02790818+0.00000000e+00j -0.01420914+0.00000000e+00j
   0.03631967+0.00000000e+00j ... -0.0001902 +1.71268825e-05j
  -0.00022316+0.00000000e+00j -0.00012367+0.00000000e+00j]
 [ 0.02494414+0.00000000e+00j -0.01234238+0.00000000e+00j
   0.01728277+0.00000000e+00j ... -0.00036335-1.31850265e-04j
   0.00071144+0.00000000e+00j  0.0009609 +0.00000000e+00j]
 ...
 [ 0.03233427+0.00000000e+00j -0.01901201+0.00000000e+00j
   0.00990284+0.00000000e+00j ... -0.01645983+2.75168967e-03j
   0.01612859+0.00000000e+00j  0.018665  +0.00000000e+00j]
 [ 0.02779346+0.00000000e+00j  0.00871042+0.00000000e+00j
  -0.02408747+0.00000

In [10]:
from sklearn.decomposition import PCA
pca=PCA(0.95)
X_pca=pca.fit_transform(X)
print("After Applying PCA, Shape is",X_pca.shape)
print('----------------------------------')
print('Previous Shape was',X.shape)

After Applying PCA, Shape is (1797, 29)
----------------------------------
Previous Shape was (1797, 64)


In [11]:
pca.explained_variance_ratio_

array([0.14890594, 0.13618771, 0.11794594, 0.08409979, 0.05782415,
       0.0491691 , 0.04315987, 0.03661373, 0.03353248, 0.03078806,
       0.02372341, 0.02272697, 0.01821863, 0.01773855, 0.01467101,
       0.01409716, 0.01318589, 0.01248138, 0.01017718, 0.00905617,
       0.00889538, 0.00797123, 0.00767493, 0.00722904, 0.00695889,
       0.00596081, 0.00575615, 0.00515158, 0.0048954 ])

In [12]:
pca.n_components_

29

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=9)
logistic=LogisticRegression()
logistic.fit(X_train,y_train)
print(logistic.score(X_test,y_test))

0.9611111111111111


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
X_train_pca,X_test_pca,y_train_pca,y_test_pca=train_test_split(X_pca,y,test_size=0.2,random_state=9)
logistic1=LogisticRegression()
logistic1.fit(X_train_pca,y_train_pca)
print(logistic1.score(X_test_pca,y_test_pca))

0.95


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# **Dimension Reduction by no of components or columns or features**

In [15]:
pca1=PCA(n_components=2)
X_pca1=pca1.fit_transform(X)
print(X_pca1.shape)


(1797, 2)


In [16]:
print(X_pca1)
print('---------------------------------------')
print(pca1.explained_variance_ratio_)

[[ -1.25946488  21.27488343]
 [  7.95761252 -20.7687006 ]
 [  6.99192104  -9.95598558]
 ...
 [ 10.80128417  -6.96025036]
 [ -4.87210009  12.42394921]
 [ -0.34439082   6.36555211]]
---------------------------------------
[0.14890594 0.13618771]


In [17]:
X_train_pca1,X_test_pca1,y_train_pca1,y_test_pca1=train_test_split(X_pca1,y,test_size=0.2,random_state=9)
logistic2=LogisticRegression()
logistic2.fit(X_train_pca1,y_train_pca1)
print(logistic2.score(X_test_pca1,y_test_pca1))

0.5888888888888889


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
